name: 'Get Last Artifact'
description: 'Retrieves the last artifact with a certain name'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - run: print %ENV;
      shell: perl {0}
    - run: ${GITHUB_ACTION_PATH}/action.pl
      shell: bash
      with:
        GITHUB_TOKEN: ${{ github.token }}
