name: 'Get Last Artifact'
description: 'Retrieves the last artifact with a certain name'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: liblwp-protocol-https-perl
        version: 1.0
    - run: ${GITHUB_ACTION_PATH}/action.pl
      shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
