name: Local checks
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - id: running-tests
      name: Run local tests
      uses: ./
    - name: Creates artifact
      run: echo "$GITHUB_RUN_ID" > last_run_id
    - name: Upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: last_run_id
        path: last_run_id
