name: Local checks
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - id: running-tests
      uses: ./
    - name: Test
      run: print %ENV;
      shell: perl {0}
    - name: Creates artifact
      run: echo "$GITHUB_RUN_ID" > last_run_id
    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: last_run_id
        path: last_run_id
