name: Local checks
on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Testing
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Libraries for testing
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: liblwp-protocol-https-perl
        version: 1.0
    - name: Perl test
      run: prove
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - id: running-tests
      name: Run local tests
      uses: ./
      with:
        artifact-name: last_run_id
    - name: After tests, check that the file has been retrieved
      run: ls
    - name: Creates artifact
      run: echo "$GITHUB_RUN_ID" > last_run_id
    - name: Upload test artifact
      uses: actions/upload-artifact@v4
      with:
        name: last_run_id
        path: last_run_id
